name: for coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install dependcies
        run: sudo apt-get update && sudo apt-get install -y lcov gcc g++
      - name: confogure cmake
        env:
          CXX: g++
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCOLLECT_COVERAGE=ON
      - name: build
        run: cmake --build build
      - name: tests
        run: ctest --test-dir build --output-on-failure
      - name: coverage
        run: |
          lcov --capture --directory build --output-file coverage_raw.info --ignore-errors mismatch,unexecuted
          lcov --extract coverage_raw.info '*/banking/Account.cpp' '*/banking/Transaction.cpp' --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info --ignore-errors unused
          lcov --list coverage.info
      - name: push to coverals
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          file: coverage_result.info
