name: for coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install dependcies
        run: sudo apt-get update && sudo apt-get install -y lcov gcc g++
      - name: confogure cmake
        env:
          CXX: g++
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCODE_COVERAGE=ON
      - name: build
        run: cmake --build build
      - name: tests
        run: ctest --test-dir build --output-on-failure
      - name: coverage
        run: |
            cd build

            # Собираем покрытие через gcov
            find . -name "*.gcno" -exec gcov -p {} \;

            # Создаём отчёт
            lcov --capture \
                --directory . \
                --output-file coverage.info \
                --ignore-errors mismatch \
                --no-external \
                --rc lcov_branch_coverage=0  # ← Отключаем branch coverage

            # Извлекаем наши файлы
            lcov --extract coverage.info \
                '*/lab05/banking/*' \
                '*/banking/*' \
                --output-file coverage_result.info \
                --ignore-errors mismatch \
                --rc lcov_branch_coverage=0

            lcov --list coverage_result.info
      - name: push to coverals
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          file: coverage_result.info
